### ISSUE TITLE
No such file or directory - /tools/android

### ISSUE THREAD

**Issue by oguzhanaslann** [joshrlesch/fastlane-plugin-instrumented_tests#14]
I installed the plugin and write a lane as : 
` desc "Run all instrumented tests"
   lane :instrumented_test do
        instrumented_tests(
          avd_name: "Nexus_5_API_25_Test",
          avd_package: "'system-images;android-19;google_apis;x86'",
          avd_abi: "google_apis/x86",
        )

   end`

but when I try to run the my instrumented tests via "fastlane instrumented_test" , it gives me this error.
`+------------------+---------------------------+
|                 Lane Context                 |
+------------------+---------------------------+
| DEFAULT_PLATFORM | android                   |
| PLATFORM_NAME    | android                   |
| LANE_NAME        | android instrumented_test |
+------------------+---------------------------+
[09:58:49]: No such file or directory - /tools/android

/usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-plugin-instrumented_tests-0.2.0/lib/fastlane/plugin/instrumented_tests/actions/instrumented_tests_action.rb:43:in ``': No such file or directory - /tools/android (Errno::ENOENT)
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-plugin-instrumented_tests-0.2.0/lib/fastlane/plugin/instrumented_tests/actions/instrumented_tests_action.rb:43:in `delete_old_emulators'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-plugin-instrumented_tests-0.2.0/lib/fastlane/plugin/instrumented_tests/actions/instrumented_tests_action.rb:12:in `run'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:46:in `block (2 levels) in parsing_binding'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.197.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `load'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `<main>'
`

Is there any way to fix this issue ?

**Comment by JordanLongstaff** [comment]
You need to specify the Android SDK directory. You can do it either through the `sdk_path` argument or the `ANDROID_HOME` environment variable. If you use the environment variable, either add it to the command (`ANDROID_HOME=<your_sdk_path> fastlane instrumented_test`) or to your PATH.
